image: java:8

cache:
  paths:
    - /root/.gradle/

before_script:
  # Enable the usage of sources over https
  - apt-get update -yqq
  - apt-get install apt-transport-https -yqq
  # Log the java version
  - java -version

build:
  script:
    - chmod +x gradlew
    - ./gradlew setupCIWorkspace build uploadArchives
    - mkdir artifacts
    - cp build/libs/* artifacts/
  artifacts:
    paths:
    - artifacts/
